name: autoformat

on:
  push:
    paths:
      - "/**/*.py"

jobs:
  autoformat_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Execute Black
        id: format
        run: |
          black ./**/*.py
      - name: Auto commit
        if: steps.format.outputs.status == "changed"
        run: |
            git config user.name = "github-actions"
            git config user.email = "github-actions[bot]@users.noreply.github.com"
            git commit -am "auto build by github actions" --allow-empty
            git push
