name: autoformat

on:
  push:
    paths:
      - "*.py"

jobs:
  autoformat_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Execute Black
        id: format
        run: |
          black ./**/*.py
      - name: Check for modified files
        id: git-check
        run: echo '::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)'
      - name: Auto commit
        if: ${{ steps.git-check.outputs.mofidied == 'true' }}
        run: |
            git config user.name = "github-actions"
            git config user.email = "github-actions[bot]@users.noreply.github.com"
            git add -u
            git commit -m "auto format by github actions"
            git push origin
